name: Build and deploy Node.js app to Azure Web App - Synoptix

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: |
          npm run build
          if [ -d ".next" ]; then
            echo "Build completed successfully"
          else
            echo "Build failed - .next directory not found"
            exit 1
          fi

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip .next public package.json package-lock.json next.config.js node_modules

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Install production dependencies
        run: npm ci --omit=dev

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2BC0FF302D0745A3BCE3ACA5C7AC3BE5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7E4F22EB57B644DEBBF1C732D9DD2B5D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1FDFECC512EB4FE18F3CA7BAA09A235F }}

      - name: Set SCM_DO_BUILD_DURING_DEPLOYMENT to false
        run: echo "SCM_DO_BUILD_DURING_DEPLOYMENT=false" >> $GITHUB_ENV

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Synoptix'
          slot-name: 'Production'
          package: .
          start-command: "npx next start -p 8080"
